# Generated by Django 5.2.3 on 2026-01-26 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_year', models.PositiveIntegerField()),
                ('final_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'ordering': ['-first_year'],
            },
        ),
        migrations.CreateModel(
            name='AdminCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Colateral',
                'verbose_name_plural': 'Colateral',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Wind', 'Viento'), ('String', 'Cuerdas'), ('Percussion', 'Percusión'), ('Other', 'Otros')], max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MusicalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('academic_center', 'Centro Académico'), ('center', 'Núcleo'), ('extension', 'Extensión'), ('module', 'Módulo'), ('management', 'Gerencia')], max_length=30)),
                ('code', models.CharField(default=0, max_length=100)),
                ('bathrooms_quantity', models.PositiveIntegerField(default=0, null=True)),
                ('wc_quantity', models.PositiveIntegerField(default=0, null=True)),
                ('municipality', models.CharField(blank=True, max_length=70)),
                ('parish', models.CharField(blank=True, max_length=70)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('director_name', models.CharField(blank=True, max_length=70)),
            ],
            options={
                'verbose_name': 'Núcleo',
                'verbose_name_plural': 'Núcleos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Programa Académico Orquestal', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='OrchestralProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, help_text='Cédula o Pasaporte del estudiante.', max_length=8)),
                ('has_document_id', models.BooleanField(default=True, help_text='Marque si el estudiante posee cédula o pasaporte.')),
                ('nationality', models.CharField(choices=[('V', 'Venezolano/a'), ('E', 'Extranjero/a')], help_text="Nacionalidad del estudiante ('V' para Venezolano, 'E' para Extranjero).", max_length=1)),
                ('names', models.CharField(help_text='Nombres del estudiante.', max_length=30)),
                ('lastnames', models.CharField(help_text='Apellidos del estudiante.', max_length=30)),
                ('born_date', models.DateField(help_text='Fecha de nacimiento del estudiante (debe tener más de 5 años).')),
                ('gender', models.CharField(choices=[('Femenine', 'Femenino'), ('Masculine', 'Masculino')], help_text='Género del estudiante.', max_length=10)),
                ('address', models.TextField(help_text='Dirección del estudiante (máximo 300 caracteres).', max_length=300, null=True)),
                ('home_phone', models.CharField(blank=True, help_text='Número de teléfono de casa.', max_length=11, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico del estudiante.', max_length=50, null=True)),
                ('cellphone', models.CharField(blank=True, help_text='Número de teléfono celular.', max_length=11, null=True)),
                ('academic_institution_name', models.CharField(help_text='Nombre del Plantel Educativo.', max_length=70, null=True)),
                ('academic_institution_address', models.TextField(help_text='Dirección del Plantel Educativo.', max_length=200, null=True)),
                ('academic_degree', models.CharField(help_text='Grado académico.', max_length=30, null=True)),
                ('academic_institution_type', models.CharField(help_text='Tipo de Plantel (Privado, Mixto, etc.)', max_length=30, null=True)),
                ('housing_type', models.CharField(help_text='Tipo de Vivienda (Casa, Edificio, Apartamento, Quinta, etc.)', max_length=30, null=True)),
                ('housing_condition', models.CharField(help_text='Estado de la Vivienda (Propia, Alquilada, etc.)', max_length=30, null=True)),
                ('number_people_living_housing', models.IntegerField(default=1, help_text='Cantidad de personas que habitan en la Vivienda.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('allergies', models.TextField(blank=True, help_text='Indique las alergias del estudiante. Dejar en blanco si no tiene o se desconocen.', max_length=150, null=True)),
                ('regular_medical_treatment', models.TextField(blank=True, help_text='Indique si el estudiante toma tratamiento médico regular. Dejar en blanco en caso contrario.', max_length=200, null=True)),
                ('medical_report', models.TextField(blank=True, help_text='Indique datos del informe médico del estudiante. Dejar en blanco en caso contrario.', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='StudentRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(help_text='Parentesco del representante legal.', max_length=20, null=True)),
                ('fullname', models.CharField(help_text='Nombre completo del representante legal.', max_length=70, null=True)),
                ('born_date', models.DateField(help_text='Fecha de nacimiento del representante legal', null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Soltero/a'), ('Married', 'Casado/a'), ('Divorced', 'Divorciado/a'), ('Widowed', 'Viudo/a'), ('Concubinage', 'Concubinato'), ('Stable union', 'Unión estable')], help_text='Estado civil del representante legal.', max_length=20, null=True)),
                ('document_id', models.CharField(help_text='Cédula o Pasaporte del representante legal.', max_length=8, null=True)),
                ('nationality', models.CharField(choices=[('V', 'Venezolano/a'), ('E', 'Extranjero/a')], help_text='Nacionalidad del representante legal.', max_length=1, null=True)),
                ('profession', models.CharField(help_text='Profesión u oficio del representante legal.', max_length=30, null=True)),
                ('address', models.TextField(blank=True, help_text='Dirección de Habitación (Solo si es diferente a la del Beneficiario).', max_length=300, null=True)),
                ('home_phone', models.CharField(blank=True, help_text='Número de Habitación (Solo si es diferente a la del Beneficiario).', max_length=11, null=True)),
                ('cellphone', models.CharField(help_text='Número de teléfono celular.', max_length=11, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico del representante legal.', max_length=50, null=True)),
                ('workplace', models.CharField(blank=True, help_text='Lugar de trabajo del representante legal.', max_length=40, null=True)),
                ('job_title', models.CharField(blank=True, help_text='Cargo del representante legal.', max_length=30, null=True)),
                ('office_phone', models.CharField(blank=True, help_text='Número de Oficina.', max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código del trabajador.', max_length=9, unique=True)),
                ('document_id', models.CharField(blank=True, help_text='Cédula o Pasaporte del trabajador.', max_length=8, unique=True)),
                ('names', models.CharField(blank=True, help_text='Nombres del trabajador.', max_length=100)),
                ('lastnames', models.CharField(blank=True, help_text='Apellidos del trabajador.', max_length=100)),
                ('born_date', models.DateField(help_text='Fecha de nacimiento del trabajador')),
                ('admission_date', models.DateField(help_text='Fecha de ingreso del trabajador')),
                ('proffesional', models.BooleanField(default=False)),
                ('type', models.CharField(help_text='Tipo de trabajador.', max_length=20)),
                ('nationality', models.CharField(choices=[('V', 'Venezolano/a'), ('E', 'Extranjero/a')], help_text="Nacionalidad del trabajador ('V' para Venezolano, 'E' para Extranjero).", max_length=1)),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], help_text='Género del trabajador.', max_length=1)),
                ('id_admin_collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admincollateral')),
                ('id_admin_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adminposition')),
                ('id_musical_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.musicalcenter')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Nombre completo del contacto de emergencia.', max_length=100, verbose_name='Nombre completo')),
                ('relationship', models.CharField(help_text='Parentesco del contacto de emergencia.', max_length=50, verbose_name='Parentesco')),
                ('cellphone', models.CharField(help_text='Teléfono del contacto de emergencia.', max_length=11, verbose_name='Teléfono')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='app.student')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='id_legal_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_legal_parent', to='app.studentrelative'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_relative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_relative', to='app.studentrelative'),
        ),
        migrations.CreateModel(
            name='DetailAcademicInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateField()),
                ('type', models.CharField(choices=[('New admission', 'Nuevo ingreso'), ('Re-entry', 'Reingreso'), ('Data update', 'Actualización de datos'), ('Re-enrollment', 'Reinscripción regular')], max_length=30)),
                ('id_academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicperiod')),
                ('id_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instrument')),
                ('id_musical_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.musicalcenter')),
                ('id_musical_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.musicalprogram')),
                ('id_orchestral_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.orchestralproject')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'verbose_name': 'Detalle de Inscripción Académica',
                'verbose_name_plural': 'Detalles de Inscripción Académica',
                'ordering': ['id_academic_period'],
                'unique_together': {('id_student', 'id_academic_period')},
            },
        ),
    ]
