from .academic_period import AcademicPeriod
from .detail_academic_inscription import DetailAcademicInscription
from .musical_center import MusicalCenter
from .musical_program import MusicalProgram
from .orchestal_project import OrchestralProject
from .employee import Employee
from .admin_position import AdminPosition
from .admin_collateral import AdminCollateral
from .instrument import Instrument
from .student_relative import StudentRelative
from .student import Student
from .emergency_contact import EmergencyContact